### ISSUE TITLE
Phil and Sanaz unable to run tests

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-openstack-test#30]
This error was not present until I installed:
pip install python-neutronclient
pip install f5-sdk
pip install git+https://github.com/F5Networks/f5-openstack-test.git

Does anything strike you right off that might have caused it?

Thanks,  Sanaz & Phil

(test) BLD-ML-SKERGAN:functional skergan$ py.test --bigip-netloc=10.190.3.64 --auth-netloc=10.190.4.131 -v test_CLUDS.py
Traceback (most recent call last):
  File "/Users/skergan/test/bin/py.test", line 11, in <module>
    sys.exit(main())
  File "/Users/skergan/test/lib/python2.7/site-packages/_pytest/config.py", line 39, in main
    config = _prepareconfig(args, plugins)
  File "/Users/skergan/test/lib/python2.7/site-packages/_pytest/config.py", line 118, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "/Users/skergan/test/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/Users/skergan/test/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/skergan/test/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/Users/skergan/test/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 595, in execute
    return _wrapped_call(hook_impl.function(_args), self.execute)
  File "/Users/skergan/test/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 249, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "/Users/skergan/test/lib/python2.7/site-packages/_pytest/helpconfig.py", line 28, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/Users/skergan/test/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
    _reraise(_ex)  # noqa
  File "/Users/skergan/test/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 264, in __init__
    self.result = func()
  File "/Users/skergan/test/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
    res = hook_impl.function(*args)
  File "/Users/skergan/test/lib/python2.7/site-packages/_pytest/config.py", line 861, in pytest_cmdline_parse
    self.parse(args)
  File "/Users/skergan/test/lib/python2.7/site-packages/_pytest/config.py", line 966, in parse
    self._preparse(args, addopts=addopts)
  File "/Users/skergan/test/lib/python2.7/site-packages/_pytest/config.py", line 927, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/Users/skergan/test/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 501, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/Users/skergan/test/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2228, in load
    self.require(_args, *_kwargs)
  File "/Users/skergan/test/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2245, in require
    items = working_set.resolve(reqs, env, installer)
  File "/Users/skergan/test/lib/python2.7/site-packages/pkg_resources/**init**.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Babel 2.3.3 (/Users/skergan/test/lib/python2.7/site-packages), Requirement.parse('Babel!=2.3.0,!=2.3.1,!=2.3.2,!=2.3.3,>=1.3'), set(['python-heatclient']))

**Comment by zancas** [comment]
@szakeri @pskergan 
Please examine the contents of:

`https://github.com/F5Networks/f5-openstack-test/blob/0eb06c99637794523cb917e663e7893abf72abed/setup.py`

Notice that the commit-hash is part of the url you are visiting.

Inside the setup.py file, in the call to the `setup` function you'll see a keyword parameter: "install_requires"

Notice that "install_requires" is assigned to a list of strings that includes "_neutronclient_" and "_f5-sdk_"...

This is the file and parameter that determines the behavior of `pip install THISDIRECTORY` when `THISDIRECTORY` is the directory that contains this `setup.py`.

BTW, the correct Pythonic name for this directory (the one that contains `setup.py`) is the "distribution root".

So, first off your procedure should NOT run:

```
pip install python-neutronclient
pip install f5-sdk
```

because that logic is implied by:

```
pip install git+https://github.com/F5Networks/f5-openstack-test.git
```

**Comment by zancas** [comment]
One fix is to run 'pip uninstall Babel', and then 'pip install Babel--2.2.0".

We need to understand which chain of dependencies is causing this conflict.
